version: '3.8'
services:
  localstack:
    image: localstack/localstack:3.0
    container_name: integration_aws_test
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sqs
      - DEBUG=1
      - ACTIVATE_PRO=0  # Примусово вимикаємо запит ліцензії